name: Build and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: ./mvnw -Djavacpp.platform=linux-x86_64 -DskipTests clean verify

    - name: Clean up target directory
      run: rm -rf target/*.jar*

    - uses: actions/upload-artifact@master
      with:
        name: autosnake
        path: target/
        retention-days: 1

  python:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@master
      with:
        name: autosnake
        path: target/

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v3

    - name: Run one training iteration
      run: cd py ; python train_AC.py --test ; python train_convAC.py --test

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: autosnake
        path: target/

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Unit and Integration Tests
      run: mvn -Djavacpp.platform=linux-x86_64 verify
